---
title: "Rebecca Hoover"
subtitle: "Resume for applying for an Imaginary Job on 09/03/2024"
format: docx
editor: visual
---

+--------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+
| ## Fieldwork and Volunteer Experience  {style="color: dark green"}                                                                                     | ## Core Skills {style="color: dark green"}                                                           |
|                                                                                                                                                        |                                                                                                      |
| **Maymont, Richmond VA — *Intern and Horticulture Volunteer***                                                                                         | -   Fieldwork                                                                                        |
|                                                                                                                                                        |                                                                                                      |
| Fall 2023 - June 2024                                                                                                                                  | -   Manual Labor / Maintenance                                                                       |
|                                                                                                                                                        |                                                                                                      |
| -   new stuff                                                                                                                                          | -   Esri Suite / RStudio / Microsoft Office                                                          |
|                                                                                                                                                        |                                                                                                      |
| -   new stuff                                                                                                                                          | -   Peer Leadership\                                                                                 |
|                                                                                                                                                        |                                                                                                      |
| -   new stuff                                                                                                                                          | ## Education {style="color: dark green"}                                                             |
|                                                                                                                                                        |                                                                                                      |
| **Maymont Project, Richmond VA — *Independent Study***                                                                                                 | **VCU, Richmond VA — Bachelor of Science**                                                           |
|                                                                                                                                                        |                                                                                                      |
| Fall 2023 - June 2024                                                                                                                                  | **Expected in 2025**                                                                                 |
|                                                                                                                                                        |                                                                                                      |
| -   Proficient in project management including scoping, setting timelines, deliverables, and client management.                                        | -   Major: Environmental Studies                                                                     |
|                                                                                                                                                        |                                                                                                      |
| -   Skilled in field data collection using traditional methods and new technologies such as Geographic Information System (GIS) Mobile Apps.           | -   3.270 GPA                                                                                        |
|                                                                                                                                                        |                                                                                                      |
| -   Experienced in building and deploying ArcGIS Online Story Maps and Field Maps.                                                                     | -   Preceptor for Urban Ecology                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Conducted an iTree analysis to determine ecosystem services provided by trees.                                                                     | **Thomas Dale High School, Chester VA — *Advanced Studies Diploma***                                 |
|                                                                                                                                                        |                                                                                                      |
| **VCU** **Rice Rivers Center, Charles City VA — *Data Collection and Invasive Species Removal Volunteer***                                             | ***2022***                                                                                           |
|                                                                                                                                                        |                                                                                                      |
| **AltBreaks Spring Break 2023, False Cape State Park VA — *Park Maintenance Volunteer***                                                               | -   4.3966 GPA (Top 10% of Class)                                                                    |
|                                                                                                                                                        |                                                                                                      |
| ## Work Experience {style="color: dark green"}                                                                                                         | -   Science Club (President/Co-President)\                                                           |
|                                                                                                                                                        |                                                                                                      |
| **VCU Recwell, Richmond VA — OAP TFWS Training and Grants Intern**                                                                                     | ## Certifications {style="color: dark green"}                                                        |
|                                                                                                                                                        |                                                                                                      |
| August 2024 - PRESENT                                                                                                                                  | -   ServSafe Food Handler — Expires 10/27/24                                                         |
|                                                                                                                                                        |                                                                                                      |
| -   Scheduled and trained new employees, monitored their performance, and provided assistance and guidance as needed.                                  | -   Adult and Pediatric CPR/AED/First Aid— Expires in 2025                                           |
|                                                                                                                                                        |                                                                                                      |
| -   Researched grants that align with the Outdoor Adventure Program and wrote grant proposals so that they me be granted. \*\*rewrite this\*\*         | -   Governor's Early College Certificate — May 2022                                                  |
|                                                                                                                                                        |                                                                                                      |
| -   Coordinated with ProStaff and student managers to assess the workflow and tasks needed throughout the semester.                                    | Working Towards — \@VCU                                                                              |
|                                                                                                                                                        |                                                                                                      |
| **VCU Recwell, Richmond VA — OAP Outing Rental Center Manager**                                                                                        | -   River Studies and Leadership Certificate                                                         |
|                                                                                                                                                        |                                                                                                      |
| May 2024 - PRESENT                                                                                                                                     | -   Outdoor Leadership Certificate\                                                                  |
|                                                                                                                                                        |                                                                                                      |
| -   Scheduled and trained new employees, monitored their performance, and provided assistance and guidance as needed.                                  | ## Notable Coursework {style="color: dark green"}                                                    |
|                                                                                                                                                        |                                                                                                      |
| -   Managed inventory of rental equipment and ensured proper maintenance and upkeep.                                                                   | -   Invasive Species Management in Urban Parks — Spring 2024, A                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Coordinated with ProStaff and team members to assess the workflow and tasks needed during each work shift.                                         | -   Intro to Geographic Information Systems — Spring 2024, A (Change This)                           |
|                                                                                                                                                        |                                                                                                      |
| **Maymont, Richmond VA — Horticulture Intern**                                                                                                         | -   Urban Ecology Independent Study — Fall 2023, A\                                                  |
|                                                                                                                                                        |                                                                                                      |
| May 2024 - June 2024                                                                                                                                   | ## References {style="color: dark green"}                                                            |
|                                                                                                                                                        |                                                                                                      |
| -   Participated in hands-on horticultural training sessions, expanding knowledge of various gardening techniques and practices.                       | Available upon request                                                                               |
|                                                                                                                                                        |                                                                                                      |
| -   Identified plant diseases and researched methods for mitigation.                                                                                   | \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |
|                                                                                                                                                        |                                                                                                      |
| -   Performed regular data updates by integrating new information into existing GIS databases, ensuring up-to-date resources for project stakeholders. |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| **VCU Recwell, Richmond VA — OAP Outing Rental Center Attendant**                                                                                      |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| **October 2023 - May 2024**                                                                                                                            |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Handled maintenance and repair requests to keep properties in good condition and maintain renter satisfaction.                                     |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Responded quickly to customer inquiries, answering questions and offering insight into operations of the Outing Rental Center, and Climbing Wall.  |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Conducted regular inspections of rental equipment to ensure safety and quality standards were met.                                                 |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| **Chick-Fil-A, Chester VA — Back of House Team Member / Marketing Associate**                                                                          |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| March 2022 - PRESENT                                                                                                                                   |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Performed daily cleaning and maintenance tasks to keep kitchen clean and organized.                                                                |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Coordinated with kitchen staff, working hard to stay ahead of the demand of 1 minute and exceed customer expectations.                             |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Removed all kitchen garbage and placed it in designated container areas; including lifting and carrying heavy material.                            |                                                                                                      |
|                                                                                                                                                        |                                                                                                      |
| -   Assisted in upkeep of inventory to provide accurate store supply and worked flexible schedules and extra shifts to meet business needs.            |                                                                                                      |
+========================================================================================================================================================+======================================================================================================+
+--------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+
